/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // stockSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "youtube",
    {
      type: "category",
      label: "1 月折扣碼/優惠碼統整",
      collapsed: false,
      items: [
        "youtube/20230202",
        "youtube/20230201",
        "youtube/20230131",
        "youtube/20230130",
        "youtube/20230129",
        "youtube/20230128",
        "youtube/20230127",
        "youtube/20230126",
        "youtube/20230125",
        "youtube/20230124",
        "youtube/20230123",
        "youtube/20230122",
        "youtube/20230121",
        "youtube/20230120",
        "youtube/20230119",
        "youtube/20230118",
      ],
    }
  ],
  stockSidebar: [
    "stock",
    {
      type: "category",
      label: "股市選股",
      collapsed: false,
      items: [
        "stock/20230202",
        "stock/20230201",
        "stock/20230131",
      ],
    }
  ],
};

module.exports = sidebars;
